module.exports = {
  mockUser1: {
    email: 'yani@gmail.com',
    firstName: 'yani',
    lastName: 'yani',
    playerNumber: '1',
    defaultPosition: 'CB',
  },
  mockUser2: {
    email: 'jose@gmail.com',
    firstName: 'jose',
    lastName: 'jose',
    playerNumber: '2',
    defaultPosition: 'CB',
  },
  mockUser3: {
    email: 'Andres@gmail.com',
    firstName: 'Andres',
    lastName: 'Andres',
    playerNumber: '3',
    defaultPosition: 'CB',
  },
  mockUser4: {
    email: 'jasja@gmail.com',
    firstName: 'jasja',
    lastName: 'mariaaaaaa',
    playerNumber: '4',
    defaultPosition: 'CB',
  },
  mockUser5: {
    email: 'manuel@gmail.com',
    firstName: 'manuel',
    lastName: 'manuel',
    playerNumber: '5',
    defaultPosition: 'CB',
  },
  mockUser6: {
    email: 'salva@gmail.com',
    firstName: 'salva',
    lastName: 'salva',
    playerNumber: '6',
    defaultPosition: 'CB',
  },
  mockUser7: {
    email: 'jorge@gmail.com',
    firstName: 'jorge',
    lastName: 'jorge',
    playerNumber: '7',
    defaultPosition: 'CB',
  },
  mockUser8: {
    email: 'iniesta@gmail.com',
    firstName: 'iniesta',
    lastName: 'iniesta',
    playerNumber: '8',
    defaultPosition: 'CB',
  },
  mockUser9: {
    email: 'berni@gmail.com',
    firstName: 'berni',
    lastName: 'berni',
    playerNumber: '9',
    defaultPosition: 'CB',
  },
  mockUser10: {
    email: 'PabloEscobar@gmail.com',
    firstName: 'Pablo',
    lastName: 'Escobar',
    playerNumber: '10',
    defaultPosition: 'CB',
  },
  mockUser11: {
    email: 'ElChapoGuzman@gmail.com',
    firstName: 'Chapo',
    lastName: 'Guzman',
    playerNumber: '11',
    defaultPosition: 'CB',
  },
  mockUser1: {
    email: 'Alcapone@gmail.com',
    firstName: 'Alcapone',
    lastName: 'El Capo',
    playerNumber: '12',
    defaultPosition: 'CB',
  },
};
